/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import securechar_server.DbServices;
import securechar_server.UserInfo;

/**
 *
 * @author Mohammed Muayad
 */
public class AuthenticationManagementForm extends javax.swing.JFrame {

     
    private DbServices DB;
    private UserInfo USER ;
    
    public AuthenticationManagementForm() {
       initComponents();
       this.setLocationRelativeTo(null);
       updateData();
    }
    
    private void updateData(){
        DB = new DbServices();
        allDataTbl.setModel(DbUtils.resultSetToTableModel(DB.all()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullNmeLbl = new javax.swing.JLabel();
        DobLbl = new javax.swing.JLabel();
        departmentLbl = new javax.swing.JLabel();
        UserIDLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        DobTxt = new javax.swing.JTextField();
        departmentTxt = new javax.swing.JTextField();
        IDTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        insertBtn = new javax.swing.JButton();
        SearchByIDBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        allDataTbl = new javax.swing.JTable();
        showPassChk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(536, 440));
        setMinimumSize(new java.awt.Dimension(536, 440));
        setPreferredSize(new java.awt.Dimension(536, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(536, 440));
        getContentPane().setLayout(null);

        fullNmeLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fullNmeLbl.setText("Full Name:");
        getContentPane().add(fullNmeLbl);
        fullNmeLbl.setBounds(10, 90, 60, 14);

        DobLbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        DobLbl.setText("DOB");
        getContentPane().add(DobLbl);
        DobLbl.setBounds(286, 91, 26, 13);

        departmentLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        departmentLbl.setText("Department");
        getContentPane().add(departmentLbl);
        departmentLbl.setBounds(10, 141, 63, 14);

        UserIDLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        UserIDLbl.setText("User ID");
        getContentPane().add(UserIDLbl);
        UserIDLbl.setBounds(10, 40, 60, 14);

        PasswordLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PasswordLbl.setText("Password");
        getContentPane().add(PasswordLbl);
        PasswordLbl.setBounds(270, 40, 48, 14);
        getContentPane().add(fullNameTxt);
        fullNameTxt.setBounds(91, 87, 119, 20);
        getContentPane().add(DobTxt);
        DobTxt.setBounds(330, 87, 147, 20);
        getContentPane().add(departmentTxt);
        departmentTxt.setBounds(91, 138, 386, 20);
        getContentPane().add(IDTxt);
        IDTxt.setBounds(91, 37, 119, 20);
        getContentPane().add(PasswordTxt);
        PasswordTxt.setBounds(330, 40, 149, 20);

        insertBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(insertBtn);
        insertBtn.setBounds(20, 370, 100, 30);

        SearchByIDBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SearchByIDBtn.setText("Search by ID");
        SearchByIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIDBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchByIDBtn);
        SearchByIDBtn.setBounds(140, 370, 110, 30);

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn);
        updateBtn.setBounds(260, 370, 100, 30);

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(390, 370, 100, 30);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        allDataTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Title 2", "Title 3", "Title 4"
            }
        ));
        allDataTbl.setEnabled(false);
        allDataTbl.setGridColor(new java.awt.Color(153, 204, 255));
        jScrollPane2.setViewportView(allDataTbl);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 180, 510, 168);

        showPassChk.setBackground(new java.awt.Color(255, 255, 255));
        showPassChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassChkActionPerformed(evt);
            }
        });
        getContentPane().add(showPassChk);
        showPassChk.setBounds(480, 40, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/b6.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 550, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void clearTxt(){
        IDTxt.setText("");
        PasswordTxt.setText("");
        fullNameTxt.setText("");
        DobTxt.setText("");
        departmentTxt.setText("");
    }

    private void SearchByIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIDBtnActionPerformed
      
        USER = new UserInfo();
        USER=DB.SearchId(IDTxt.getText());
        fullNameTxt.setText(USER.getFullName());
        departmentTxt.setText(USER.getDepartment());
        PasswordTxt.setText(USER.getPass());
        DobTxt.setText(USER.getDOB());
    }//GEN-LAST:event_SearchByIDBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
         int chk;
         USER = new UserInfo();
         USER.setUserID(IDTxt.getText());
         USER.setPass(PasswordTxt.getText ());
         USER.setFullName(fullNameTxt.getText());
         USER.setDOB(DobTxt.getText());
         USER.setDepartment(departmentTxt.getText());
         USER.setAdmin("false");
         chk= DB.InsertUser(USER);
         //Insertion successful
         if(chk==1){
             clearTxt();
             updateData();
         }

    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         int chk;
         USER = new UserInfo();
         USER.setUserID(IDTxt.getText());
         USER.setPass(PasswordTxt.getText ());
         USER.setFullName(fullNameTxt.getText());
         USER.setDOB(DobTxt.getText());
         USER.setDepartment(departmentTxt.getText());
         chk = DB.updateUser(USER);
         updateData();
         //updarte successful
         if(chk==1){
             clearTxt();
           
         }
        
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(IDTxt.getText().length()>0){ // if the ID field is not empty do
           DB.deleteUser(IDTxt.getText());
           updateData();
           clearTxt();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void showPassChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassChkActionPerformed
       if(showPassChk.isSelected()){
           PasswordTxt.setEchoChar((char)0);
       }else{
           PasswordTxt.setEchoChar('*');
       }
    }//GEN-LAST:event_showPassChkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AuthenticationManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DobLbl;
    private javax.swing.JTextField DobTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JButton SearchByIDBtn;
    private javax.swing.JLabel UserIDLbl;
    private javax.swing.JTable allDataTbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel departmentLbl;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JLabel fullNmeLbl;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox showPassChk;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
